name: Docker Image

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    strategy:
      matrix:
        os: [ubuntu-latest]
        go-version: [1.23.1-bookworm]
        tailscale-version: [v1.76.6, v1.78.1]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      # https://docs.docker.com/build/ci/github-actions/multi-platform/
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ matrix.tailscale-version }}-{{sha}}

      - uses: docker/build-push-action@v6
        id: push
        with:
          platforms: linux/amd64,linux/arm64
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            GO_VERSION=${{ matrix.go-version }}
            TAILSCALE_VERSION=${{ matrix.tailscale-version }}
